### ISSUE TITLE
demo? Test?

### ISSUE THREAD

**Issue by ag-coder** [cabbiepete/jQuery-Share-Email#2]
hello your plugin is a handy idea, but how does it work?
do i have to use all the setup-code in your test.html?

do you have a simple demo page?

thanks anyway 4 share your plugin and work.

greets

**Comment by cabbiepete** [comment]
Include the script from the src folder and then call 

$(<selector>).shareEmail();

Where <selector> is a jQuery selector for the element.

I'll update the README and get a little demo going though that's a good idea.

**Comment by ag-coder** [comment]
hey cabbiepete thanks for your response!

well i cant get it to run!
i have always a error in firebug as well:
" $.tmpl is not a function
  $.tmpl(o.template, o).appendTo($(this)); "

i include jquery the newest Version 1.6.2  and your script.
and this code

a href="#" class="email">Email</a

script type="text/javascript">
    $('.email').shareEmail();
</script

thanks 4 help

**Comment by cabbiepete** [comment]
Oh great point it does depend on the jquery tmpl plugin also. Sorry I forgot as I always include this in projects.

You can get this from https://github.com/jquery/jquery-tmpl/blob/master/jquery.tmpl.min.js if you include that also.

I would have found this shortly when I attempt to get the demo going but thanks for the heads up.

**Comment by ag-coder** [comment]
ahhh YES it work now! 
it was just this missing tmpl-script.

thanks 4 your fast response

**Comment by cabbiepete** [comment]
Re opening until I get the demo site done

**Comment by cabbiepete** [comment]
Got the demo site up as a github pages site. http://cabbiepete.github.com/jQuery-Share-Email/
